#!/bin/bash
# Copyright Mandriva S/A all rights reserved
# This file is part of Mandriva Server Setup
#
# MSS is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# MSS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MSS; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
# ######################   Description of this program  ###################################
#
#  This program basically does 5 things
#  * backup squid configuration file squid.conf
#  * query existing settings in the base.ini file generated by MDS installer and
#  configure the template files with the information collected
#  *creates 3 new user groups in LDAP base
#  *replace original files for templates files  
#  *restart squid and validates installation
# Autor: Alexandre Proença  alexandre@mandriva.com.br | linuxloco@gmail.com
# Date: 10/08/2012 


if [ "`id -u`" != "0" ]; then
	echo "Error, must be root user"
	exit 1
fi

. '../functions.sh'

proxy_template="templates/squid.conf.tpl"
squidnow_template="templates/squidnow.pl"
sarg_template="templates/sarg.conf"
sargtmp_template="templates/sarg.conf.tpl"
ldif_template="templates/group_ldap.dif"
ldiftmp_template="templates/group_ldap.dif.tmp"
proxy_conf="/etc/squid/squid.conf"
proxy_rules="/etc/squid/rules"
my_domain=`cat /etc/mmc/plugins/base.ini | egrep ^baseDN | cut -c10-100`
user_dn=`cat /etc/mmc/plugins/base.ini | egrep ^rootName | cut -c12-300`
pass_dn=`cat /etc/mmc/plugins/base.ini | egrep ^password | cut -c12-100 | grep ^[^e]`

echo "7Backup is running..."
sleep 2
backup /etc/squid/squid.conf
cat $proxy_template > /etc/squid/squid.conf
sed -i "s/\@DN\@/$my_domain/" /etc/squid/squid.conf
cat $ldiftmp_template > $ldif_template
sed -i "s/\@DN\@/$my_domain/" $ldif_template 
cat $sargtmp_template > $sarg_template 
sed -i "s/\@DN\@/$my_domain/" $sarg_template 
sed -i "s/\@PASS\@/$pass_dn/" $sarg_template

echo "7Creating groups in LDAP base..."
sleep 2
/usr/bin/ldapadd -f $ldif_template -x -D "$user_dn" -w $pass_dn  

if [ $? -ne 0 ]; then
	echo "2Something went wrong while creating the groups on LDAP base"
	exit 1
else
	echo "8Groups greated  successfully."
	sleep 2
fi


echo "7Creating files and directories... "
sleep 2
# create a new directory
if [ ! -d $proxy_rules ]; then
    mkdir -p $proxy_rules
fi
/bin/cp -rf templates/rules/* $proxy_rules 
/bin/chmod -R 664 $proxy_rules

/bin/cp -f $squidnow_template /vaw/www/cgi-bin/
/bin/chmod 666 /var/log/squid/access.log

cat $sarg_template > /etc/sarg/sarg.conf

/sbin/service squid restart > /dev/null 2>&1
if [ $? -eq 0 ]; then 
	echo "7Service squid reloaded succesfully."
else 
	echo "2Service squid fails restarting. Check /var/log/syslog"; sleep 1; exit 1
fi

chkconfig squid on
echo 8The Proxy service was successfully installe.
echo 7You can now configure your Internet rules from the management interface : http://@HOSTNAME@/mmc/

exit 0
		    
