#!/bin/bash
# Copyright Mandriva S/A all rights reserved
# This file is part of Mandriva Server Setup
#
# MSS is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# MSS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MSS; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
# ######################   Description of this program  ###################################
#
#  This program basically does 5 things
#  * backup squid configuration file squid.conf
#  * query existing settings in the base.ini file generated by MDS installer and
#  configure the template files with the information collected
#  *creates 3 new user groups in LDAP base
#  *replace original files for templates files
#  *restart squid and validates installation
# Autor: Alexandre Proença - alexandre@mandriva.com.br | linuxloco@gmail.com
#        Jean-Philippe Braun - jpbraun@mandriva.com
# Date: 10/08/2012


if [ "`id -u`" != "0" ]; then
	echo "Error, must be root user"
	exit 1
fi

. '../functions.sh'

proxy_template="templates/squid.conf.tpl"
sarg_template="templates/sarg.conf.tpl"
squidnow_template="templates/squidnow.pl"
proxy_conf="/etc/squid/squid.conf"
sarg_conf="/etc/sarg/sarg.conf"
proxy_rules="/etc/squid/rules"

mds_base_ini="/etc/mmc/plugins/base.ini"
my_domain=`grep '^baseDN' $mds_base_ini | sed 's/^.*[[:space:]]\+=[[:space:]]\+//'`
pass_dn=`grep '^password' $mds_base_ini | sed 's/^.*[[:space:]]\+=[[:space:]]\+//'`
pass_dn_e=`escape_sed $mdspass`

echo "0Configuring squid..."
backup $proxy_conf
cat $proxy_template > $proxy_conf
sed -i "s/\@DN\@/$my_domain/" $proxy_conf
# handle 64bit
if [ -d /usr/lib64 ]; then
    sed -i "s!/usr/lib!/usr/lib64!g" $proxy_conf
fi

backup $sarg_conf
cat $sarg_template > $sarg_conf
sed -i "s/\@DN\@/$my_domain/" $sarg_conf
sed -i "s/\@PASS\@/$pass_dn_e/" $sarg_conf

echo "0Creating groups..."
python create-groups.py
if [ $? -ne 0 ]; then
	echo "2Something went wrong while creating the user groups."
	exit 1
else
	echo "0Groups created successfully."
fi

echo "0Creating files and directories... "
# create a new directory
if [ ! -d $proxy_rules ]; then
    mkdir -p $proxy_rules
fi
/bin/cp -rf templates/rules/* $proxy_rules
/bin/chmod -R 664 $proxy_rules

/bin/cp -f $squidnow_template /vaw/www/cgi-bin/
/bin/chmod 666 /var/log/squid/access.log

restart_service squid
enable_service squid

echo 8The Proxy service is running
echo 7You can now configure your Internet rules from the management interface : http://@HOSTNAME@/mmc/

exit 0
